/* ===== BLOCK: Block 15 ===== */

/* ===== CODE: SEPARATION INTO YEAR, MONTH,DAY ===== */

ALTER TABLE SATELLITE_ALL ADD COLUMN ET_YEAR VARCHAR;

ALTER TABLE SATELLITE_ALL ADD COLUMN ET_MONTH VARCHAR;

ALTER TABLE SATELLITE_ALL ADD COLUMN ET_DAY VARCHAR;

ALTER TABLE SATELLITE_ALL ADD COLUMN OT_YEAR VARCHAR;

ALTER TABLE SATELLITE_ALL ADD COLUMN OT_MONTH VARCHAR;

ALTER TABLE SATELLITE_ALL ADD COLUMN OT_DAY VARCHAR;

-- VKLADAME ROK,MESIC A DEN Z TABULKY END OF TRANSMISSION
UPDATE SATELLITE_ALL
SET 
    ET_YEAR = TRIM(SUBSTR(END_OF_TRANSMISSION, 1, 4)),
    ET_MONTH = CASE
        WHEN END_OF_TRANSMISSION LIKE '% Jan%' THEN '01'
        WHEN END_OF_TRANSMISSION LIKE '% Feb%' THEN '02'
        WHEN END_OF_TRANSMISSION LIKE '% Mar%' THEN '03'
        WHEN END_OF_TRANSMISSION LIKE '% Apr%' THEN '04'
        WHEN END_OF_TRANSMISSION LIKE '% May%' THEN '05'
        WHEN END_OF_TRANSMISSION LIKE '% Jun%' THEN '06'
        WHEN END_OF_TRANSMISSION LIKE '% Jul%' THEN '07'
        WHEN END_OF_TRANSMISSION LIKE '% Aug%' THEN '08'
        WHEN END_OF_TRANSMISSION LIKE '% Sep%' THEN '09'
        WHEN END_OF_TRANSMISSION LIKE '% Oct%' THEN '10'
        WHEN END_OF_TRANSMISSION LIKE '% Nov%' THEN '11'
        WHEN END_OF_TRANSMISSION LIKE '% Dec%' THEN '12'
        ELSE NULL
    END,
    ET_DAY = TRIM(
        CASE
            WHEN LENGTH(END_OF_TRANSMISSION) > 8 THEN SUBSTR(END_OF_TRANSMISSION, -2, 2)
            ELSE NULL
        END);

-- VKLADAME ROK,MESIC A DEN Z TABULKY END OF OPERATION
UPDATE SATELLITE_ALL
SET 
    OT_YEAR = TRIM(SUBSTR(END_OF_OPERATION, 1, 4)),
    OT_MONTH = CASE
        WHEN END_OF_OPERATION LIKE '% Jan%' THEN '01'
        WHEN END_OF_OPERATION LIKE '% Feb%' THEN '02'
        WHEN END_OF_OPERATION LIKE '% Mar%' THEN '03'
        WHEN END_OF_OPERATION LIKE '% Apr%' THEN '04'
        WHEN END_OF_OPERATION LIKE '% May%' THEN '05'
        WHEN END_OF_OPERATION LIKE '% Jun%' THEN '06'
        WHEN END_OF_OPERATION LIKE '% Jul%' THEN '07'
        WHEN END_OF_OPERATION LIKE '% Aug%' THEN '08'
        WHEN END_OF_OPERATION LIKE '% Sep%' THEN '09'
        WHEN END_OF_OPERATION LIKE '% Oct%' THEN '10'
        WHEN END_OF_OPERATION LIKE '% Nov%' THEN '11'
        WHEN END_OF_OPERATION LIKE '% Dec%' THEN '12'
        ELSE NULL
    END,
    OT_DAY = TRIM(
        CASE
            WHEN LENGTH(END_OF_OPERATION) > 8 THEN SUBSTR(END_OF_OPERATION, -2, 2)
            ELSE NULL
        END);

/* ===== CODE: ADDING OF 01 ===== */

-- KDE JSOU NULLY VE MESICE NEBO DNE ALE ZAROVEN VE STATUSU JE NECO NASPSANO A ROK NENI NULL, PRIDAVAME 01    
UPDATE SATELLITE_ALL
SET 
    ET_MONTH = CASE 
        WHEN ET_MONTH IS NULL AND (STATUS = 'No longer transmitting') THEN '01'
        ELSE ET_MONTH
    END,
    ET_DAY = CASE 
        WHEN ET_DAY IS NULL AND (STATUS = 'No longer transmitting') THEN '01'
        ELSE ET_DAY
    END
WHERE 
    ET_YEAR IS NOT NULL;

UPDATE SATELLITE_ALL
SET 
    OT_MONTH = CASE 
        WHEN OT_MONTH IS NULL AND (STATUS = 'No longer transmitting') THEN '01'
        ELSE OT_MONTH
    END,
    OT_DAY = CASE 
        WHEN OT_DAY IS NULL AND (STATUS = 'No longer transmitting') THEN '01'
        ELSE OT_DAY
    END
WHERE 
    OT_YEAR IS NOT NULL;

/* ===== CODE: TRANSMISSION_END, OPERATION_END ===== */

--NAHRADIME MEZERY NULL PROTOZE UKAZUJOU VE DETAILU A S NIMA NEDA VYTVARIT DATUM 
UPDATE SATELLITE_ALL
SET ET_DAY = NULL
WHERE ET_DAY = '';

-- PRIDAVAME KONECNE SLOUPCI
ALTER TABLE SATELLITE_ALL ADD COLUMN TRANSMISSION_END DATE;

ALTER TABLE SATELLITE_ALL ADD COLUMN OPERATION_END DATE;

-- PRIDAVAME CELY DATUM ZE JEDNOTLIVYCH SLOUPCI
UPDATE SATELLITE_ALL
SET TRANSMISSION_END = DATE_FROM_PARTS(ET_YEAR::INT, ET_MONTH::INT, ET_DAY::INT)
WHERE ET_YEAR IS NOT NULL 
AND ET_MONTH IS NOT NULL 
AND ET_DAY IS NOT NULL;

-- PRIDAVAME CELY DATUM ZE JEDNOTLIVYCH SLOUPCI
UPDATE SATELLITE_ALL
SET OPERATION_END = DATE_FROM_PARTS(OT_YEAR::INT, OT_MONTH::INT, OT_DAY::INT)
WHERE OT_YEAR IS NOT NULL 
AND OT_MONTH IS NOT NULL 
AND OT_DAY IS NOT NULL;

/* ===== CODE: DROP UNNESSESARY COLUMNS ===== */

--ZBAVIME SE VSECH SLOUPCU KTERE NEPOTREBUJEME

ALTER TABLE SATELLITE_ALL DROP COLUMN OT_DAY;

ALTER TABLE SATELLITE_ALL DROP COLUMN OT_MONTH;

ALTER TABLE SATELLITE_ALL DROP COLUMN OT_YEAR;

ALTER TABLE SATELLITE_ALL DROP COLUMN ET_DAY;

ALTER TABLE SATELLITE_ALL DROP COLUMN ET_MONTH;

ALTER TABLE SATELLITE_ALL DROP COLUMN ET_YEAR;

ALTER TABLE SATELLITE_ALL DROP COLUMN END_OF_TRANSMISSION;

ALTER TABLE SATELLITE_ALL DROP COLUMN END_OF_OPERATION;
