/* ===== BLOCK: Block 17 ===== */

/* ===== CODE: OWNER: UPDATED_FULL_NAME ===== */

ALTER TABLE OWNER ADD COLUMN UPDATED_FULL_NAME VARCHAR;

UPDATE OWNER 
SET UPDATED_FULL_NAME = FCN.UPDATED_FULL_NAME 
FROM "fixed_name-Sheet1" AS FCN 
WHERE OWNER.OWNER_COUNTRY = FCN.OWNER_COUNTRY;

/* ===== CODE: OWNER: FIXED_CODE ===== */

UPDATE OWNER
SET OWNER_COUNTRY = FCT.FIXED_CODE
FROM "FIXED_CODE-Sheet1" AS FCT
WHERE OWNER.OWNER_COUNTRY = FCT.OWNER_COUNTRY;

/* ===== CODE: OWNER:REGION_CONTINENT ===== */

ALTER TABLE OWNER ADD COLUMN REGION VARCHAR;

ALTER TABLE OWNER ADD COLUMN CONTINENT VARCHAR;

UPDATE OWNER
SET REGION = RC.BUSINESS_REGION
FROM "REGION_CONTINENT-Sheet1" AS RC
WHERE OWNER.OWNER_COUNTRY = RC.OWNER_COUNTRY;

UPDATE OWNER
SET CONTINENT = RC.CONTINENT
FROM "REGION_CONTINENT-Sheet1" AS RC
WHERE OWNER.OWNER_COUNTRY = RC.OWNER_COUNTRY;
