/* ===== BLOCK: Block 13 ===== */

/* ===== CODE: DATE_TABLE ===== */

CREATE OR REPLACE TABLE DATE_TABLE AS
    SELECT CAST(DATEADD(DAY, seq4(),'1957-10-04') AS DATE) AS TI_DATE
        , TO_CHAR(TI_DATE, 'YYYY MON DD') AS FULL_DATE
        , DAY(TI_DATE) AS TI_DAY
        , MONTH(TI_DATE) AS TI_MONTH
        , YEAR(TI_DATE) AS TI_YEAR
        , DAYNAME(TI_DATE) AS DAY_NAME
        , DAYOFWEEK(TI_DATE) AS NUMBER_DAY
        , TO_CHAR(TI_DATE, 'MON') AS MONTH_NAME
        , TO_CHAR(TI_DATE, 'YYYY MON') AS YEAR_MONTH
        , CONCAT('Q', QUARTER(TI_DATE)) AS QUARTER
        , CONCAT(TI_YEAR, '/', QUARTER) AS YEAR_QUARTER
  FROM TABLE(GENERATOR(ROWCOUNT => 24472)) v 
  ORDER BY 1;
