/* ===== BLOCK: Block 2 ===== */

/* ===== CODE: LAUNCH_SITE_ALLT ===== */

CREATE OR REPLACE TABLE LAUNCH_SITE_ALLT AS
SELECT
    DENSE_RANK() OVER (ORDER BY LST1.LS_NAME) AS ID_LAUNCHSITE,
    LST1.LS_NAME,
    LST2.PIECE_LS,
    LST1.LS_FULLNAME,
    LST1.LS_COUNTRY,
    LST1.LONGITUDE,
    LST1.LATITUDE
FROM 
    LAUNCH_SITE_T1 AS LST1
LEFT JOIN 
    LAUNCH_SITE_T2 AS LST2 ON LST1.LS_NAME = LST2.LS_NAME;
