/* ===== BLOCK: Block 18 ===== */

/* ===== CODE: AGENCY_COMPLETE:CODE ===== */

UPDATE AGENCY_COMPLETE AS ACM
SET AGENCY_COUNTRY = ACD.AGENCY_CODE
FROM "AGENCY_COUNTRY_CODE-Sheet1" AS ACD
WHERE ACM.AGENCY_COUNTRY = ACD.AGENCY_COUNTRY;

/* ===== CODE: AGENCY:NAME_REGION_CONTINENT ===== */

ALTER TABLE AGENCY_COMPLETE ADD COLUMN AG_FULL_COUNTRY_NAME VARCHAR;

ALTER TABLE AGENCY_COMPLETE ADD COLUMN AG_REGION VARCHAR;

ALTER TABLE AGENCY_COMPLETE ADD COLUMN AG_CONTINENT VARCHAR;

UPDATE AGENCY_COMPLETE AS AC
SET AG_FULL_COUNTRY_NAME = ANRC.AG_COUNTRY_NAME
FROM "AG_NAME_REGION_CONTINENT-Sheet1" AS ANRC
WHERE AC.AGENCY_COUNTRY = ANRC.AGENCY_CODE;

UPDATE AGENCY_COMPLETE AS AC
SET AG_REGION = ANRC.AG_REGION
FROM "AG_NAME_REGION_CONTINENT-Sheet1" AS ANRC
WHERE AC.AGENCY_COUNTRY = ANRC.AGENCY_CODE;

UPDATE AGENCY_COMPLETE AS AC
SET AG_CONTINENT = ANRC.AG_CONTINENT
FROM "AG_NAME_REGION_CONTINENT-Sheet1" AS ANRC
WHERE AC.AGENCY_COUNTRY = ANRC.AGENCY_CODE;
