/* ===== BLOCK: Block 14 ===== */

/* ===== CODE: DROP COLUMNS agency_name, piece, piece_ls ===== */

ALTER TABLE SATELLITE_ALL DROP COLUMN AGENCY_NAME;

ALTER TABLE LAUNCH_FINALT DROP COLUMN PIECE;

ALTER TABLE LAUNCH_SITE_ALLT DROP COLUMN PIECE_LS;
