/* ===== BLOCK: Block 19 ===== */

/* ===== CODE: LS:NEW_CODE ===== */

UPDATE LAUNCH_SITE_ALLT AS LSA
SET LS_COUNTRY = LNC.LS_NEW_CODE
FROM "LS_NEW_CODE_TABLE-Sheet1" AS LNC
WHERE LSA.LS_COUNTRY = LNC.LS_COUNTRY;

/* ===== CODE: LS:NAME_REGION_CONT ===== */

ALTER TABLE LAUNCH_SITE_ALLT ADD COLUMN LS_FULL_COUNTRY VARCHAR;

ALTER TABLE LAUNCH_SITE_ALLT ADD COLUMN LS_REGION VARCHAR;

ALTER TABLE LAUNCH_SITE_ALLT ADD COLUMN LS_CONTINENT VARCHAR;

UPDATE LAUNCH_SITE_ALLT AS LSAT
SET LS_FULL_COUNTRY = LSNRC.LS_FULL_COUNTRY_NAME
FROM "LS_NAME_REGION_CONT-Sheet1" AS LSNRC
WHERE LSAT.LS_COUNTRY = LSNRC.LS_NEW_CODE;

UPDATE LAUNCH_SITE_ALLT AS LSAT
SET LS_REGION = LSNRC.LS_REGION
FROM "LS_NAME_REGION_CONT-Sheet1" AS LSNRC
WHERE LSAT.LS_COUNTRY = LSNRC.LS_NEW_CODE;

UPDATE LAUNCH_SITE_ALLT AS LSAT
SET LS_CONTINENT = LSNRC.LS_CONTINENT
FROM "LS_NAME_REGION_CONT-Sheet1" AS LSNRC
WHERE LSAT.LS_COUNTRY = LSNRC.LS_NEW_CODE;
